# Generated by Django 3.0 on 2020-01-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0002_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
