# Generated by Django 3.0 on 2020-01-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0003_inquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='id',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='company',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='id_inquiry',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='state',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='zip_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
