# Generated by Django 3.0 on 2020-01-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0005_auto_20200104_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='id_inquiry',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
