# Generated by Django 3.0 on 2020-01-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0007_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
