# Generated by Django 3.0 on 2020-01-05 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0008_auto_20200104_2324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='inquiry',
        ),
    ]
