# Generated by Django 3.0 on 2020-01-05 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0009_delete_inquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
