# Generated by Django 3.0 on 2020-01-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0013_auto_20200105_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='inquiry',
            fields=[
                ('id_inquiry', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=90)),
                ('email', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='', max_length=200)),
                ('company', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('state', models.CharField(default='', max_length=200)),
                ('zip_code', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
