# Generated by Django 3.0 on 2020-01-05 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0016_auto_20200105_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='id_inquiry',
            new_name='msg_id',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='name_i',
            new_name='name',
        ),
    ]
